name = "LoadCell"
uuid = "66f42eca-bd93-4e2a-8f90-f4369287fd74"
authors = ["Electrons1014 <24guppra@gmail.com>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1.2.1"